/* SPDX-FileCopyrightText: 2026 Blender Authors
 *
 * SPDX-License-Identifier: GPL-2.0-or-later */

#ifdef GPU_SHADER
#  pragma once
#  include "gpu_shader_compat.hh"
#endif

#include "gpu_shader_create_info.hh"

GPU_SHADER_CREATE_INFO(compositor_terrain_primitive)
LOCAL_GROUP_SIZE(16, 16)
PUSH_CONSTANT(int2, domain_size)
PUSH_CONSTANT(int, primitive_type)
PUSH_CONSTANT(int, vector_is_single)
PUSH_CONSTANT(float, scale)
PUSH_CONSTANT(float, height)
PUSH_CONSTANT(float, detail)
PUSH_CONSTANT(float, roughness)
PUSH_CONSTANT(float, distortion)
PUSH_CONSTANT(float, lacunarity)
PUSH_CONSTANT(float, seed)
PUSH_CONSTANT(float2, offset)
SAMPLER(0, sampler2D, vector_tx)
IMAGE(0, SFLOAT_16_16_16_16, write, image2D, height_img)
COMPUTE_SOURCE("compositor_terrain_primitive.glsl")
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(compositor_terrain_pack)
LOCAL_GROUP_SIZE(16, 16)
PUSH_CONSTANT(int2, domain_size)
SAMPLER(0, sampler2D, height_tx)
IMAGE(0, SFLOAT_16_16_16_16, write, image2D, field_img)
COMPUTE_SOURCE("compositor_terrain_pack.glsl")
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(compositor_terrain_erosion_flux)
LOCAL_GROUP_SIZE(16, 16)
PUSH_CONSTANT(int2, domain_size)
PUSH_CONSTANT(float, dt)
PUSH_CONSTANT(float, gravity)
SAMPLER(0, sampler2D, field_tx)
SAMPLER(1, sampler2D, flux_tx)
IMAGE(0, SFLOAT_16_16_16_16, write, image2D, flux_img)
COMPUTE_SOURCE("compositor_terrain_erosion_flux.glsl")
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(compositor_terrain_erosion_apply)
LOCAL_GROUP_SIZE(16, 16)
PUSH_CONSTANT(int2, domain_size)
PUSH_CONSTANT(float, dt)
PUSH_CONSTANT(float, rain)
PUSH_CONSTANT(float, evaporation)
PUSH_CONSTANT(float, capacity)
PUSH_CONSTANT(float, solubility)
PUSH_CONSTANT(float, deposition)
PUSH_CONSTANT(float, downcutting)
PUSH_CONSTANT(float, thermal)
PUSH_CONSTANT(float, talus)
PUSH_CONSTANT(float, orographic)
PUSH_CONSTANT(float2, rain_dir)
SAMPLER(0, sampler2D, field_tx)
SAMPLER(1, sampler2D, flux_tx)
SAMPLER(2, sampler2D, mask_tx)
IMAGE(0, SFLOAT_16_16_16_16, write, image2D, field_img)
COMPUTE_SOURCE("compositor_terrain_erosion_apply.glsl")
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(compositor_terrain_thermal)
LOCAL_GROUP_SIZE(16, 16)
PUSH_CONSTANT(int2, domain_size)
PUSH_CONSTANT(float, strength)
PUSH_CONSTANT(float, talus)
PUSH_CONSTANT(int, corners)
SAMPLER(0, sampler2D, field_tx)
SAMPLER(1, sampler2D, mask_tx)
IMAGE(0, SFLOAT_16_16_16_16, write, image2D, field_img)
COMPUTE_SOURCE("compositor_terrain_thermal.glsl")
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(compositor_terrain_hydrofix)
LOCAL_GROUP_SIZE(16, 16)
PUSH_CONSTANT(int2, domain_size)
PUSH_CONSTANT(float, amount)
PUSH_CONSTANT(float, slope)
SAMPLER(0, sampler2D, field_tx)
IMAGE(0, SFLOAT_16_16_16_16, write, image2D, field_img)
COMPUTE_SOURCE("compositor_terrain_hydrofix.glsl")
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(compositor_terrain_outputs)
LOCAL_GROUP_SIZE(16, 16)
PUSH_CONSTANT(int2, domain_size)
SAMPLER(0, sampler2D, field_tx)
SAMPLER(1, sampler2D, flux_tx)
IMAGE(0, SFLOAT_16_16_16_16, write, image2D, height_img)
IMAGE(1, SFLOAT_16_16_16_16, write, image2D, flow_img)
IMAGE(2, SFLOAT_16_16_16_16, write, image2D, sediment_img)
IMAGE(3, SFLOAT_16_16_16_16, write, image2D, wear_img)
IMAGE(4, SFLOAT_16_16_16_16, write, image2D, water_img)
COMPUTE_SOURCE("compositor_terrain_outputs.glsl")
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(compositor_terrain_simulate)
LOCAL_GROUP_SIZE(16, 16)
PUSH_CONSTANT(int2, domain_size)
PUSH_CONSTANT(int, sim_type)
PUSH_CONSTANT(float, strength)
PUSH_CONSTANT(float, coverage)
PUSH_CONSTANT(float, melt)
PUSH_CONSTANT(float, height_min)
PUSH_CONSTANT(float, height_max)
PUSH_CONSTANT(float, slope_max)
PUSH_CONSTANT(float, sea_level)
PUSH_CONSTANT(float, seed)
PUSH_CONSTANT(float, iterations)
SAMPLER(0, sampler2D, height_tx)
SAMPLER(1, sampler2D, mask_tx)
IMAGE(0, SFLOAT_16_16_16_16, write, image2D, height_img)
IMAGE(1, SFLOAT_16_16_16_16, write, image2D, mask_img)
COMPUTE_SOURCE("compositor_terrain_simulate.glsl")
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(compositor_terrain_modify)
LOCAL_GROUP_SIZE(16, 16)
PUSH_CONSTANT(int2, domain_size)
PUSH_CONSTANT(int, modify_type)
PUSH_CONSTANT(float, amount)
PUSH_CONSTANT(float, steps)
PUSH_CONSTANT(float, sharpness)
PUSH_CONSTANT(float, seed)
PUSH_CONSTANT(float, min_h)
PUSH_CONSTANT(float, max_h)
SAMPLER(0, sampler2D, height_tx)
SAMPLER(1, sampler2D, guide_tx)
IMAGE(0, SFLOAT_16_16_16_16, write, image2D, height_img)
COMPUTE_SOURCE("compositor_terrain_modify.glsl")
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(compositor_terrain_derive)
LOCAL_GROUP_SIZE(16, 16)
PUSH_CONSTANT(int2, domain_size)
PUSH_CONSTANT(int, derive_type)
PUSH_CONSTANT(float, min_v)
PUSH_CONSTANT(float, max_v)
PUSH_CONSTANT(float, softness)
PUSH_CONSTANT(float, azimuth)
SAMPLER(0, sampler2D, height_tx)
IMAGE(0, SFLOAT_16_16_16_16, write, image2D, mask_img)
COMPUTE_SOURCE("compositor_terrain_derive.glsl")
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(compositor_terrain_color)
LOCAL_GROUP_SIZE(16, 16)
PUSH_CONSTANT(int2, domain_size)
PUSH_CONSTANT(int, color_type)
PUSH_CONSTANT(float, sea_level)
PUSH_CONSTANT(float, snow_level)
PUSH_CONSTANT(float, weathering)
PUSH_CONSTANT(float4, water_color)
PUSH_CONSTANT(float4, sand_color)
PUSH_CONSTANT(float4, grass_color)
PUSH_CONSTANT(float4, rock_color)
PUSH_CONSTANT(float4, snow_color)
SAMPLER(0, sampler2D, height_tx)
SAMPLER(1, sampler2D, flow_tx)
IMAGE(0, SFLOAT_16_16_16_16, write, image2D, color_img)
COMPUTE_SOURCE("compositor_terrain_color.glsl")
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(compositor_terrain_combine)
LOCAL_GROUP_SIZE(16, 16)
PUSH_CONSTANT(int2, domain_size)
PUSH_CONSTANT(int, combine_type)
PUSH_CONSTANT(float, factor)
SAMPLER(0, sampler2D, a_tx)
SAMPLER(1, sampler2D, b_tx)
SAMPLER(2, sampler2D, mask_tx)
IMAGE(0, SFLOAT_16_16_16_16, write, image2D, height_img)
COMPUTE_SOURCE("compositor_terrain_combine.glsl")
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()
